services:
  db:
    image: postgres:16.3
    command: [ "postgres", "-c", "log_statement=all" ]
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data
    volumes:
      - ./data/pgdb:/data
    ports:
      - "5432:5432"
